
#ifndef ELEVATIONENCODER
#define ELEVATIONENCODER
#include <elapsedMillis.h>


/**
  The Elevation angle is a Rev Through Bore, which returns a 
  Servo pulse that we must decode to calculate the target setpoint.
*/
namespace ElevationEncoder{
  // This setup uses hardware interrupts to capture a pulse generated by the encoder
  // the time the pulse the "high" represents the angle of the encoder.
  // The processs is 
  // - Register the interrupt, so that every time the signal on our pin changes, 
  //   we run the ISR (Interrupt Service Routine).
  // - The ISR then captures the time, and does nothing else. These need to be *fast*, so we don't
  //   do math here. Math is slow on microprocessors.
  // - Lastly, when we need the angle we do a quick calculation to convert the last recorded 
  //   timer value into physical degrees

  int interruptPinElevation;
  elapsedMicros isrTimerElevation;
  volatile unsigned int pulseElevation=0;

  static void ISRElevationRead(){
    if(digitalRead(interruptPinElevation)==HIGH){
      //Reset our timer
      isrTimerElevation=0;    
    } else{
      pulseElevation=isrTimerElevation;
    }
  }

  /// Configure the hardware to properly interpret the signals generated by the absolute encoder
  void ConfigElevationPWM(int pin ){
    interruptPinElevation=pin; 
    pinMode(interruptPinElevation, INPUT);
    attachInterrupt(digitalPinToInterrupt(interruptPinElevation), ISRElevationRead, CHANGE);
  }

  /// Return the angle of the shooter
  int ReadElevationDegrees(){
    //Values determined empirically for the specific bot layout.
    return map(pulseElevation,1,1036,1,360)-120;
  }
}

#endif
